image: node:9

stages: 
  - test
  - build
  - gitlab-deploy

before_script: 
  - node -v
  - npm -v
  - cd client && npm install && cd ..

client_lint:
  script:
    - cd client
    - npm run lint
  stage: test

client_build:
  script:
    - cd client
    - npm run build
  stage: build
  artifacts: 
    paths:
      - client/dist
    expire_in: 2 weeks
  only:
    - master
    - web

# client deployment to gitlab pages
pages: 
  artifacts:
    paths:
      - public
  only:
    - master
    - web
  script: 
    - cd client
    - echo "module.exports={configureWebpack:{output:{publicPath:'/sscl-dictionary'},resolve:{alias:{mdl:'material-design-lite'}}},pwa:{workboxPluginMode:'InjectManifest',workboxOptions:{swSrc:'src/serviceWorker.js',swDest:'service-worker.js'}},}" > vue.config.js
    - npm run build
    - mv dist ../public
  stage: gitlab-deploy
