image: node:9

stages: 
  - test
  - build

before_script: 
  - node -v
  - npm -v
  - cd client && npm install && cd ..

client_lint:
  script:
    - cd client
    - npm run lint
  stage: test

client_build:
  script:
    - cd client
    - npm run build
  stage: build
  artifacts: 
    paths:
      - client/dist
    expire_in: 2 weeks
  only:
    - master
    - web